Repository team-tokpik/tokpik-be, pull requests merged in 2024-09, with the labels that each got.

#2 프로젝트 초기 설정(#1)
  .github/issue_template.md
  .github/pull_request_template.md
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
  src/main/java/org/example/tokpik_be/TokpikBeApplication.java
  src/main/resources/application.yml
  src/test/java/org/example/tokpik_be/TokpikBeApplicationTests.java
Labels: :receipt: chore

#9 변경된 요구사항에 따른 User 엔티티 수정
  Dockerfile
  src/main/java/org/example/tokpik_be/user/domain/User.java
Labels: :lady_beetle: fix

#11 카카오 소셜 로그인, 프로필 생성
  src/main/java/org/example/tokpik_be/common/ApiExceptionResponse.java
  src/main/java/org/example/tokpik_be/common/BaseTimeEntity.java
  src/main/java/org/example/tokpik_be/exception/GlobalExceptionHandler.java
  src/main/java/org/example/tokpik_be/exception/LoginException.java
  src/main/java/org/example/tokpik_be/login/controller/LoginController.java
  src/main/java/org/example/tokpik_be/login/dto/response/KakaoUserResponse.java
  src/main/java/org/example/tokpik_be/login/dto/response/LoginResponse.java
  src/main/java/org/example/tokpik_be/login/service/KakaoApiClient.java
  src/main/java/org/example/tokpik_be/login/service/LoginCommandService.java
  src/main/java/org/example/tokpik_be/user/controller/UserController.java
  src/main/java/org/example/tokpik_be/user/converter/GenderConverter.java
  src/main/java/org/example/tokpik_be/user/domain/User.java
  src/main/java/org/example/tokpik_be/user/dto/request/UserMakeProfileRequest.java
  src/main/java/org/example/tokpik_be/user/repository/UserRepository.java
  src/main/java/org/example/tokpik_be/user/service/UserCommandService.java
  src/main/java/org/example/tokpik_be/user/service/UserQueryService.java
  src/main/java/org/example/tokpik_be/util/JwtUtil.java
  src/test/java/org/example/tokpik_be/support/ControllerTestSupport.java
  src/test/java/org/example/tokpik_be/user/controller/UserControllerTest.java
  src/test/java/org/example/tokpik_be/user/service/UserCommandServiceTest.java
Labels: :computer: feat, :test_tube: test

#13 사용자 대화 태그 조회
  src/main/java/org/example/tokpik_be/tag/controller/TopicTagController.java
  src/main/java/org/example/tokpik_be/tag/domain/TopicTag.java
  src/main/java/org/example/tokpik_be/tag/dto/response/UserTopicTagResponse.java
  src/main/java/org/example/tokpik_be/tag/entity/UserTopicTag.java
  src/main/java/org/example/tokpik_be/tag/repository/TopicTagRepository.java
  src/main/java/org/example/tokpik_be/tag/repository/UserTopicTagRepository.java
  src/main/java/org/example/tokpik_be/tag/service/TopicTagService.java
  src/main/java/org/example/tokpik_be/user/domain/User.java
  src/test/java/org/example/tokpik_be/tag/controller/TopicTagControllerTest.java
Labels: :computer: feat, :test_tube: test

#16 access token refresh 기능 개발
  src/main/java/org/example/tokpik_be/exception/LoginException.java
  src/main/java/org/example/tokpik_be/login/controller/LoginController.java
  src/main/java/org/example/tokpik_be/login/dto/request/AccessTokenRefreshRequest.java
  src/main/java/org/example/tokpik_be/login/dto/response/AccessTokenRefreshResponse.java
  src/main/java/org/example/tokpik_be/login/service/LoginCommandService.java
  src/main/java/org/example/tokpik_be/user/service/UserQueryService.java
  src/main/java/org/example/tokpik_be/util/JwtUtil.java
  src/test/java/org/example/tokpik_be/login/controller/LoginControllerTest.java
  src/test/java/org/example/tokpik_be/login/service/LoginCommandServiceTest.java
Labels: :computer: feat, :test_tube: test

#18 access token refresh 기능 수정
  src/main/java/org/example/tokpik_be/login/service/LoginCommandService.java
  src/main/java/org/example/tokpik_be/user/domain/User.java
  src/main/java/org/example/tokpik_be/user/service/UserQueryService.java
  src/main/java/org/example/tokpik_be/util/JwtUtil.java
  src/test/java/org/example/tokpik_be/login/service/LoginCommandServiceTest.java
Labels: :lady_beetle: fix, :test_tube: test

#22 access token refresh시 refresh token도 갱신토록 수정
  src/main/java/org/example/tokpik_be/login/dto/response/AccessTokenRefreshResponse.java
  src/main/java/org/example/tokpik_be/login/service/LoginCommandService.java
  src/test/java/org/example/tokpik_be/login/controller/LoginControllerTest.java
  src/test/java/org/example/tokpik_be/login/service/LoginCommandServiceTest.java
Labels: :lady_beetle: fix

#23 사용자 대화 태그 수정
  src/main/java/org/example/tokpik_be/exception/TagException.java
  src/main/java/org/example/tokpik_be/tag/controller/TopicTagController.java
  src/main/java/org/example/tokpik_be/tag/dto/request/UserTopicTagsRequest.java
  src/main/java/org/example/tokpik_be/tag/repository/UserTopicTagRepository.java
  src/main/java/org/example/tokpik_be/tag/service/TopicTagService.java
Labels: :computer: feat

#25 사용자 장소 태그 조회, 수정
  src/main/java/org/example/tokpik_be/tag/controller/PlaceTagController.java
  src/main/java/org/example/tokpik_be/tag/dto/request/UserPlaceTagsRequest.java
  src/main/java/org/example/tokpik_be/tag/dto/response/UserPlaceTagResponse.java
  src/main/java/org/example/tokpik_be/tag/entity/UserPlaceTag.java
  src/main/java/org/example/tokpik_be/tag/repository/PlaceTagRepository.java
  src/main/java/org/example/tokpik_be/tag/repository/UserPlaceTagRepository.java
  src/main/java/org/example/tokpik_be/tag/service/PlaceTagService.java
Labels: :computer: feat

#30 대화 주제 조회시 생성된 주제 저장
  .github/workflows/cd.yml
  src/main/java/org/example/tokpik_be/tag/entity/UserPlaceTag.java
  src/main/java/org/example/tokpik_be/tag/entity/UserTopicTag.java
  src/main/java/org/example/tokpik_be/tag/service/TopicTagService.java
  src/main/java/org/example/tokpik_be/talk_topic/controller/TalkTopicController.java
  src/main/java/org/example/tokpik_be/talk_topic/domain/TalkPartner.java
  src/main/java/org/example/tokpik_be/talk_topic/domain/TalkTopic.java
  src/main/java/org/example/tokpik_be/talk_topic/dto/response/TalkTopicSearchResponse.java
  src/main/java/org/example/tokpik_be/talk_topic/dto/response/TalkTopicsSearchResponse.java
  src/main/java/org/example/tokpik_be/talk_topic/repository/TalkTopicRepository.java
  src/main/java/org/example/tokpik_be/talk_topic/service/TalkTopicCommandService.java
  src/main/java/org/example/tokpik_be/talk_topic/service/TalkTopicQueryService.java
  src/main/java/org/example/tokpik_be/user/domain/User.java
  src/main/java/org/example/tokpik_be/util/llm/client/GPTApiClient.java
  src/main/java/org/example/tokpik_be/util/llm/client/LLMApiClient.java
  src/main/java/org/example/tokpik_be/util/llm/dto/request/LLMTalkTopicSearchRequest.java
  src/main/java/org/example/tokpik_be/util/llm/dto/response/LLMTalkTopicsResponse.java
Labels: :computer: feat

#32 CD 스크립트 - 배포시 repository checkout 과정 추가
  .github/workflows/cd.yml
Labels: :receipt: chore

#36 온보딩 과정 연관 API 개발
  src/main/java/org/example/tokpik_be/tag/controller/PlaceTagController.java
  src/main/java/org/example/tokpik_be/tag/controller/TopicTagController.java
  src/main/java/org/example/tokpik_be/tag/dto/response/PlaceTagTotalResponse.java
  src/main/java/org/example/tokpik_be/tag/dto/response/TopicTagTotalResponse.java
  src/main/java/org/example/tokpik_be/tag/service/PlaceTagService.java
  src/main/java/org/example/tokpik_be/tag/service/TopicTagService.java
  src/main/java/org/example/tokpik_be/user/controller/UserController.java
  src/main/java/org/example/tokpik_be/user/domain/User.java
  src/main/java/org/example/tokpik_be/user/dto/request/UserMakeProfileRequest.java
  src/main/java/org/example/tokpik_be/user/service/UserCommandService.java
  src/test/java/org/example/tokpik_be/user/controller/UserControllerTest.java
  src/test/java/org/example/tokpik_be/user/service/UserCommandServiceTest.java
Labels: :computer: feat

#38 새 스크랩 생성, 대화 주제 스크랩 기능 개발
  .github/workflows/cd.yml
  src/main/java/org/example/tokpik_be/exception/ScrapException.java
  src/main/java/org/example/tokpik_be/exception/TalkTopicException.java
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/dto/request/ScrapCreateRequest.java
  src/main/java/org/example/tokpik_be/scrap/dto/response/ScrapCreateResponse.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
  src/main/java/org/example/tokpik_be/talk_topic/service/TalkTopicQueryService.java
Labels: :computer: feat

#41 notification token 갱신 기능 개발
  src/main/java/org/example/tokpik_be/user/controller/UserController.java
  src/main/java/org/example/tokpik_be/user/domain/User.java
  src/main/java/org/example/tokpik_be/user/dto/request/UserUpdateNotificationTokenRequest.java
  src/main/java/org/example/tokpik_be/user/service/UserCommandService.java
Labels: :computer: feat

#45 총 스크랩 수, 총 톡픽 수 조회 기능 개발
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/dto/response/ScrapCountResponse.java
  src/main/java/org/example/tokpik_be/scrap/repository/ScrapRepository.java
  src/main/java/org/example/tokpik_be/scrap/repository/ScrapTopicRepository.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
Labels: :computer: feat

#47 스크랩 삭제 기능 개발
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/domain/Scrap.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
Labels: :computer: feat

#49 대화 주제 스크랩 취소 기능 개발
  src/main/java/org/example/tokpik_be/exception/ScrapException.java
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
Labels: :computer: feat

#51 대화 주제 상세 조회 기능 개발
  src/main/java/org/example/tokpik_be/scrap/repository/QueryDslScrapRepository.java
  src/main/java/org/example/tokpik_be/talk_topic/controller/TalkTopicController.java
  src/main/java/org/example/tokpik_be/talk_topic/dto/response/TalkTopicDetailResponse.java
  src/main/java/org/example/tokpik_be/talk_topic/service/TalkTopicQueryService.java
  src/main/java/org/example/tokpik_be/util/llm/client/GPTApiClient.java
  src/main/java/org/example/tokpik_be/util/llm/client/LLMApiClient.java
  src/main/java/org/example/tokpik_be/util/llm/dto/request/LLMTalkTopicDetailRequest.java
  src/main/java/org/example/tokpik_be/util/llm/dto/response/LLMTalkTopicDetailResponse.java
Labels: :computer: feat

#53 전체 대화 종류 조회 응답 데이터 수정
  src/main/java/org/example/tokpik_be/tag/controller/PlaceTagController.java
  src/main/java/org/example/tokpik_be/tag/controller/TopicTagController.java
  src/main/java/org/example/tokpik_be/tag/dto/response/TopicTagTotalResponse.java
Labels: :lady_beetle: fix

#54 알림 조회, 삭제 기능 개발
  src/main/java/org/example/tokpik_be/config/SchedulerConfig.java
  src/main/java/org/example/tokpik_be/exception/NotificationException.java
  src/main/java/org/example/tokpik_be/notification/controller/NotificationController.java
  src/main/java/org/example/tokpik_be/notification/domain/Notification.java
  src/main/java/org/example/tokpik_be/notification/domain/NotificationTalkTopic.java
  src/main/java/org/example/tokpik_be/notification/dto/response/NotificationsResponse.java
  src/main/java/org/example/tokpik_be/notification/repository/NotificationRepository.java
  src/main/java/org/example/tokpik_be/notification/repository/NotificationTalkTopicRepository.java
  src/main/java/org/example/tokpik_be/notification/repository/QueryDslNotificationRepository.java
  src/main/java/org/example/tokpik_be/notification/service/NotificationCommandService.java
  src/main/java/org/example/tokpik_be/notification/service/NotificationQueryService.java
  src/main/java/org/example/tokpik_be/talk_topic/dto/request/TalkTopicSearchRequest.java
  src/main/java/org/example/tokpik_be/talk_topic/repository/QueryDslTalkTopicRepository.java
  src/main/java/org/example/tokpik_be/user/domain/User.java
Labels: :computer: feat

#56 삭제된 알림, 조회시 제외토록 조건 추가
  src/main/java/org/example/tokpik_be/notification/repository/QueryDslNotificationRepository.java
Labels: :lady_beetle: fix

#58 스크랩 조회 기능 개발
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/dto/response/ScrapResponse.java
  src/main/java/org/example/tokpik_be/scrap/repository/ScrapRepository.java
  src/main/java/org/example/tokpik_be/scrap/repository/ScrapTopicRepository.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
Labels: :computer: feat

#60 대화 주제 조회(검색) API, 명세 수정
  src/main/java/org/example/tokpik_be/talk_topic/dto/request/TalkTopicSearchRequest.java
Labels: :lady_beetle: fix

#62 회원 탈퇴 기능 개발
  src/main/java/org/example/tokpik_be/user/controller/UserController.java
  src/main/java/org/example/tokpik_be/user/service/UserCommandService.java
Labels: :computer: feat
