Repository team-tokpik/tokpik-be, pull requests merged in 2024-10, with the labels that each got.

#64 이용약관 조회, 개인정보정책 조회 기능 개발
  src/main/java/org/example/tokpik_be/policy/controller/PolicyController.java
  src/main/java/org/example/tokpik_be/policy/domain/Policy.java
  src/main/java/org/example/tokpik_be/policy/dto/response/PolicyResponse.java
  src/main/java/org/example/tokpik_be/policy/repository/PolicyRepository.java
  src/main/java/org/example/tokpik_be/policy/service/PolicyService.java
  src/main/java/org/example/tokpik_be/term/controller/TermController.java
  src/main/java/org/example/tokpik_be/term/domain/Term.java
  src/main/java/org/example/tokpik_be/term/dto/response/TermResponse.java
  src/main/java/org/example/tokpik_be/term/repository/TermRepository.java
  src/main/java/org/example/tokpik_be/term/service/TermService.java
Labels: :computer: feat

#66 알림 생성 기능 개발
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  .gitignore
  build.gradle
  src/main/java/org/example/tokpik_be/config/AsyncConfig.java
  src/main/java/org/example/tokpik_be/config/FcmConfig.java
  src/main/java/org/example/tokpik_be/config/SchedulerConfig.java
  src/main/java/org/example/tokpik_be/exception/NotificationException.java
  src/main/java/org/example/tokpik_be/exception/ScrapException.java
  src/main/java/org/example/tokpik_be/notification/controller/NotificationController.java
  src/main/java/org/example/tokpik_be/notification/domain/Notification.java
  src/main/java/org/example/tokpik_be/notification/domain/NotificationTalkTopic.java
  src/main/java/org/example/tokpik_be/notification/dto/request/NotificationCreateRequest.java
  src/main/java/org/example/tokpik_be/notification/dto/response/NotificationScheduledResponse.java
  src/main/java/org/example/tokpik_be/notification/event/NotificationEventListener.java
  src/main/java/org/example/tokpik_be/notification/event/NotificationSendEvent.java
  src/main/java/org/example/tokpik_be/notification/repository/QueryDslNotificationRepository.java
  src/main/java/org/example/tokpik_be/notification/service/NotificationCommandService.java
  src/main/java/org/example/tokpik_be/notification/service/NotificationQueryService.java
  src/main/java/org/example/tokpik_be/util/fcm/FcmUtil.java
  src/main/java/org/example/tokpik_be/util/fcm/dto/FcmSendNotificationRequest.java
Labels: :computer: feat

#69 알림 목록 조회시 네 개의 알림 대화 주제 종류 제공토록 수정
  src/main/java/org/example/tokpik_be/notification/dto/response/NotificationsResponse.java
  src/main/java/org/example/tokpik_be/notification/repository/QueryDslNotificationRepository.java
Labels: :computer: feat, :lady_beetle: fix

#74 알림 연관 기능 수정
  src/main/java/org/example/tokpik_be/notification/domain/Notification.java
  src/main/java/org/example/tokpik_be/notification/dto/request/NotificationCreateRequest.java
  src/main/java/org/example/tokpik_be/notification/dto/response/NotificationScheduledResponse.java
  src/main/java/org/example/tokpik_be/notification/dto/response/NotificationsResponse.java
  src/main/java/org/example/tokpik_be/notification/repository/QueryDslNotificationRepository.java
  src/main/java/org/example/tokpik_be/notification/service/NotificationCommandService.java
  src/main/java/org/example/tokpik_be/notification/service/NotificationQueryService.java
Labels: :computer: feat

#77 알림 상세 조회 기능 개발
  src/main/java/org/example/tokpik_be/exception/NotificationException.java
  src/main/java/org/example/tokpik_be/notification/controller/NotificationController.java
  src/main/java/org/example/tokpik_be/notification/dto/response/NotificationDetailResponse.java
  src/main/java/org/example/tokpik_be/notification/service/NotificationQueryService.java
Labels: :computer: feat

#79 스크랩 제목 수정 기능 개발
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/domain/Scrap.java
  src/main/java/org/example/tokpik_be/scrap/dto/request/ScrapUpdateTitleRequest.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
Labels: :computer: feat

#82 README.md 수정 시 workflow 수행하지 않게 설정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: :receipt: chore

#84 스크랩 조회 시 커서 페이징에 사용되는 파라미터명 수정
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/dto/response/ScrapResponse.java
  src/main/java/org/example/tokpik_be/scrap/repository/ScrapTopicRepository.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
Labels: :lady_beetle: fix

#86 스크랩 조회 시 커서 페이징에 사용되는 파라미터명 수정
  src/main/java/org/example/tokpik_be/scrap/controller/ScrapController.java
  src/main/java/org/example/tokpik_be/scrap/dto/response/ScrapResponse.java
  src/main/java/org/example/tokpik_be/scrap/service/ScrapService.java
Labels: :lady_beetle: fix

#87 사용자 연관 API, 비즈니스 로직 테스트 작성
  src/main/java/org/example/tokpik_be/user/service/UserCommandService.java
  src/test/java/org/example/tokpik_be/support/ServiceTestSupport.java
  src/test/java/org/example/tokpik_be/user/controller/UserControllerTest.java
  src/test/java/org/example/tokpik_be/user/service/UserCommandServiceTest.java
  src/test/java/org/example/tokpik_be/user/service/UserQueryServiceTest.java
Labels: :test_tube: test

#89 로그인 기능 수정
  src/main/java/org/example/tokpik_be/login/controller/LoginController.java
  src/main/java/org/example/tokpik_be/login/dto/request/LoginByKakaoRequest.java
  src/main/java/org/example/tokpik_be/login/service/KakaoApiClient.java
  src/main/java/org/example/tokpik_be/login/service/LoginCommandService.java
Labels: :computer: feat

#92 스크랩 연관 API, 비즈니스 로직 단위 테스트 작성
  src/test/java/org/example/tokpik_be/scrap/controller/ScrapControllerTest.java
  src/test/java/org/example/tokpik_be/scrap/service/ScrapServiceTest.java
  src/test/java/org/example/tokpik_be/support/ServiceTestSupport.java
Labels: :test_tube: test

#93 연관 대화 주제 조회 - 캐싱 도입
  build.gradle
  src/main/java/org/example/tokpik_be/config/CacheConfig.java
  src/main/java/org/example/tokpik_be/talk_topic/service/TalkTopicQueryService.java
  src/main/resources/application.yml
Labels: :computer: feat

#95 카카오 소셜 로그인 기능 수정
  src/main/java/org/example/tokpik_be/login/service/KakaoApiClient.java
Labels: :computer: feat
